// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwAWLxFYeHJ9C4eo-ovb1IaKCazqyk-7o',
    appId: '1:454368101681:web:79aaef0c3c50a2b2c3dc10',
    messagingSenderId: '454368101681',
    projectId: 'eksamensopgave-7974a',
    authDomain: 'eksamensopgave-7974a.firebaseapp.com',
    storageBucket: 'eksamensopgave-7974a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvMlHcuvM87uT91XEbHqCFiZA0pzQCnIA',
    appId: '1:454368101681:android:cffc971ed8ba2618c3dc10',
    messagingSenderId: '454368101681',
    projectId: 'eksamensopgave-7974a',
    storageBucket: 'eksamensopgave-7974a.appspot.com',
  );
}
